output "connection_id" { value = try(oci_database_tools_database_tools_connection.autonomous_database[0].id, null) }
output "connection_display_name" { value = try(oci_database_tools_database_tools_connection.autonomous_database[0].display_name, null) }
output "connection_state" { value = try(oci_database_tools_database_tools_connection.autonomous_database[0].state, null) }
output "connection_type" { value = try(oci_database_tools_database_tools_connection.autonomous_database[0].type, null) }
output "connection_string" { value = try(oci_database_tools_database_tools_connection.autonomous_database[0].connection_string, null) }
output "database_user_name" { value = try(oci_database_tools_database_tools_connection.autonomous_database[0].user_name, null) }
output "authentication_type" { value = try(oci_database_tools_database_tools_connection.autonomous_database[0].authentication_type, null) }
output "runtime_identity" { value = try(oci_database_tools_database_tools_connection.autonomous_database[0].runtime_identity, null) }
output "runtime_endpoint" { value = try(oci_database_tools_database_tools_connection.autonomous_database[0].runtime_endpoint, null) }
output "related_autonomous_database_id" { value = var.enabled ? var.autonomous_database_id : null }
output "private_endpoint_id" { value = try(oci_database_tools_database_tools_private_endpoint.autonomous_database[0].id, null) }
output "private_endpoint_display_name" { value = try(oci_database_tools_database_tools_private_endpoint.autonomous_database[0].display_name, null) }
output "private_endpoint_state" { value = try(oci_database_tools_database_tools_private_endpoint.autonomous_database[0].state, null) }
output "private_endpoint_ip" { value = try(oci_database_tools_database_tools_private_endpoint.autonomous_database[0].private_endpoint_ip, null) }
output "private_endpoint_fqdn" { value = try(oci_database_tools_database_tools_private_endpoint.autonomous_database[0].endpoint_fqdn, null) }
output "private_endpoint_vnic_id" { value = try(oci_database_tools_database_tools_private_endpoint.autonomous_database[0].private_endpoint_vnic_id, null) }
output "network_security_group_id" { value = try(oci_core_network_security_group.database_tools[0].id, null) }
output "endpoint_service_id" { value = local.selected_endpoint_service_id }
output "password_secret_id" { value = local.effective_password_secret_id }
output "vault_id" { value = try(oci_kms_vault.database_tools[0].id, null) }
output "key_id" { value = try(oci_kms_key.database_tools[0].id, null) }
